apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartsdeploy
  labels:
    app: cartsdeployapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      nodeSelector:
          "kubernetes.io/os": linux
      containers:
      - name: carts
        image: cartazuredemonacrfinal.azurecr.io/apps:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: carts
spec:
  selector:
    app: carts
  type: LoadBalancer
  ports:
  - port: 80 


    

